# Project information
site_name: INESC TEC MRDT Modified Hangfa Discovery Q2 Platform
site_url: https://sousarbarb.github.io/inesctec_mrdt_hangfa_discovery_q2/
site_author: Ricardo B. Sousa
site_description:
  Website containing all the documentation on electronics, mechanical designs,
  3D-printed components, along with all the code developed within the scope of
  the paper 'Integrating Multimodal Perception into Ground Mobile Robots'.
  The paper is a work by Ricardo B. Sousa, Héber Miguel Sobreira,
  João G. Martins, Paulo G. Costa, Manuel F. Silva, António Paulo Moreira,
  submitted at the 25th IEEE International Conference on Autonomous Robot
  Systems and Competitions (ICARSC2025).

# Repository
repo_name: sousarbarb/inesctec_mrdt_hangfa_discovery_q2
repo_url: https://github.com/sousarbarb/inesctec_mrdt_hangfa_discovery_q2

# Copyright
copyright:
  Copyright &copy; 2025 Ricardo B. Sousa et al., INESC TEC

# Configuration
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Red Hat Text
    code: JetBrains Mono
  favicon: assets/logo/inesctec_symbol_color.png
  logo: assets/logo/inesctec_symbol_white.png

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/INESCTEC
      name: GitHub
    - icon: fontawesome/brands/osi
      link: https://oss.inesctec.pt/
      name: INESC TEC Open Source Software
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/inesc-tec/
      name: LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/inesctec/
      name: Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@INESC_TEC
      name: YouTube

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter:
      base_path: 'sousarbarb/inesctec_mrdt_hangfa_discovery_q2'
      relative_path: ''
      absolute: false

# Page tree
nav:
  - About: index.md
  - Platform: content/discovery-q2.md
  - BOM: content/bom.md
  - Electronics:
    - content/electronics/index.md
    - Schematic: content/electronics/schematic.md
    - Power: content/electronics/power.md
    - Motors: content/electronics/motors.md
    - Assembly: content/electronics/assembly.md
  - SBC:
    - content/sbc/index.md
    - LattePanda 3 Delta: content/sbc/lattepanda-3-delta.md
    - LattePanda Sigma: content/sbc/lattepanda-sigma.md
    - Operating System (OS): content/sbc/os.md
    - Robot Operating System (ROS):
      - ROS 1 Noetic: content/sbc/ros-1_noetic.md
      - ROS 2 Foxy: content/sbc/ros-2_foxy.md
    - Remote Access: content/sbc/remote.md
    - Development Environment: content/sbc/dev.md
    - Firmware Setup: content/sbc/fw.md
  - Network: content/network.md
  - Sensors:
    - content/sensors/index.md
    - Inertial Measurement Units (IMUs):
      - content/sensors/imu/index.md
      - Xsens MTi-3 AHRS: content/sensors/imu/xsens_mti-3-ahrs.md
      - Xsens MTi-630 AHRS: content/sensors/imu/xsens_mti-630-ahrs.md
    - 2D Laser Scanners:
      - content/sensors/lidar2d/index.md
      - Hokuyo UST-10LX: content/sensors/lidar2d/hokuyo_ust-10lx.md
      - LDROBOT LD19: content/sensors/lidar2d/ldrobot_d300_ld19.md
      - RPLIDAR S2: content/sensors/lidar2d/slamtec_rplidar_s2.md
      - YDLIDAR X4: content/sensors/lidar2d/ydlidar_x4.md
    - 3D LiDARs:
      - content/sensors/lidar3d/index.md
      - Livox Mid-360: content/sensors/lidar3d/livox_mid-360.md
      - Ouster OS1-64: content/sensors/lidar3d/ouster_os1_64.md
      - RoboSense RS-HELIOS-5515: content/sensors/lidar3d/robosense_rs-helios_5515.md
      - Velodyne VLP-16: content/sensors/lidar3d/velodyne_vlp-16.md
    - RGBD Cameras:
      - content/sensors/rgbd/index.md
      - Intel RealSense D455: content/sensors/rgbd/intel_realsense_d455.md
      - Intel RealSense L515: content/sensors/rgbd/intel_realsense_l515.md
      - Luxonis OAK-D Pro: content/sensors/rgbd/luxonis_oak-d_pro.md
