name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
  build:
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [noetic, foxy, humble, iron]
        include:
          - ros_distro: noetic
            ros_version: 1
            ubuntu_version: 20.04
          - ros_distro: foxy
            ros_version: 2
            ubuntu_version: 20.04
          - ros_distro: humble
            ros_version: 2
            ubuntu_version: 22.04
          - ros_distro: iron
            ros_version: 2
            ubuntu_version: 22.04
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    container:
      image: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade -y
          sudo apt-get install -y git build-essential cmake
          sudo apt-get install -y libpcap-dev
          sudo apt-get install -y ros-${{ matrix.ros_distro }}-joy \
                                  ros-${{ matrix.ros_distro }}-pcl-ros
      - name: Livox-SDK2
        run: |
          git clone https://github.com/Livox-SDK/Livox-SDK2.git
          cd Livox-SDK2/
          mkdir build
          cd build/
          cmake .. && make -j
          sudo make install
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: inesctec_mrdt_hangfa_discovery_q2
          submodules: recursive
      - name: Build (ROS 1)
        if: matrix.ros_version == 1
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cd inesctec_mrdt_hangfa_discovery_q2/src
          catkin_init_workspace
          cd ..
          catkin_make --force-cmake --cmake-args -DCMAKE_BUILD_TYPE=Release
          source devel/setup.bash
        shell: bash
      - name: Build (ROS 2)
        if: matrix.ros_version == 2
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cd inesctec_mrdt_hangfa_discovery_q2
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --event-handlers status+ console_direct+ console_start_end+
          source install/setup.bash
        shell: bash
